import localFont from "next/font/local";
import "./globals.css";

const drukFont = localFont({
	src: "./fonts/Druk-Medium-Web.woff2",
	display: "swap",
	variable: "--font-drukFont",
});

const gtaFont = localFont({
	src: [
		{
			path: "./fonts/GT-America-Standard-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/GT-America-Standard-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/GT-America-Standard-Medium.woff2",
			weight: "500",
			style: "normal",
		},
	],
	variable: "--font-gtaFont",
});

export const metadata = {
	title: "MAJORITY TRAVEL",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${drukFont.variable} ${gtaFont.variable}`}>
				{children}
			</body>
		</html>
	);
}
