import localFont from "next/font/local";
import "./globals.css";
import Modal from "./components/heroComponent/modal";
import { MyContextProvider } from "./context/context";

import { useContext } from "react";
import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";

const drukFont = localFont({
	src: "./fonts/Druk-Medium-Web.woff2",
	display: "swap",
	variable: "--font-drukFont",
});

const gtaFont = localFont({
	src: [
		{
			path: "./fonts/GT-America-Standard-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/GT-America-Standard-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/GT-America-Standard-Medium.woff2",
			weight: "500",
			style: "normal",
		},
	],
	variable: "--font-gtaFont",
});

export const metadata = {
	title: "MAJORITY TRAVEL",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<MyContextProvider>
				<body
					className={`${drukFont.variable} ${gtaFont.variable} min-h-screen`}
				>
					{children}
					<Navbar />
					<Modal />
					<Footer />
				</body>
			</MyContextProvider>
		</html>
	);
}
